package com.atividade.appbank.AccountUser;

import org.json.JSONArray;
import org.json.JSONObject;

import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.net.URI;
import java.net.URL;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.text.BreakIterator;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;

import static com.atividade.appbank.AppBank.numeroContaArmazenada;
import static com.atividade.appbank.AppBank.respostaArmazenada;


/**
 *
 * @author Eliseu
 */
public class InterfaceUserLog extends javax.swing.JFrame {

    private boolean isTransferUserOpen = false;
    private boolean isInfoUserOpen = false;
    private boolean isCreateAccountOpen = false;


    /**
     * Creates new form InterfaceUserLog
     */
    public InterfaceUserLog() {
        initComponents();
        setIcon();
        setSize(800, 500);
        setLocationRelativeTo(null);
        showExtrato(numeroContaArmazenada);
        startUpdatingExtrato(numeroContaArmazenada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        moneyuser = new javax.swing.JLabel();
        nameuser = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CreateAccount = new javax.swing.JButton();
        Extrato = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMaximizedBounds(new java.awt.Rectangle(800, 500, 500, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setName("userLogin"); // NOI18N
        setResizable(false);

        moneyuser.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        moneyuser.setForeground(new java.awt.Color(16, 124, 65));
        moneyuser.setText("Saldo: {money}");

        nameuser.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        nameuser.setForeground(new java.awt.Color(16, 124, 65));
        nameuser.setText("Olá, {username}");

        jButton1.setBackground(new java.awt.Color(16, 124, 65));
        jButton1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Seus Dados no QBank");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.setRequestFocusEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(16, 124, 65));
        jButton2.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Realizar Transferência");
        jButton2.setBorder(null);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusable(false);
        jButton2.setRequestFocusEnabled(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel1.setText("Conta: {TipodeConta}");

        jPanel1.setBackground(new java.awt.Color(16, 124, 65));

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("QBank");

        File file = new File("src/main/java/com/atividade/appbank/images/logo.png");
        if (file.exists()) {
            jLabel4.setIcon(new ImageIcon(file.getAbsolutePath()));
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 105,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 36,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                .addContainerGap()));

        jLabel3.setBackground(new java.awt.Color(16, 124, 65));
        jLabel3.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(16, 124, 65));
        jLabel3.setText("Contato do Suporte QBank.support@qbank.com.br");

        CreateAccount.setBackground(new java.awt.Color(16, 124, 65));
        CreateAccount.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        CreateAccount.setForeground(new java.awt.Color(255, 255, 255));
        CreateAccount.setText("Criação de Conta");
        CreateAccount.setBorder(null);
        CreateAccount.setBorderPainted(false);
        CreateAccount.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CreateAccount.setFocusPainted(false);
        CreateAccount.setFocusable(false);
        CreateAccount.setRequestFocusEnabled(false);
        CreateAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAccountActionPerformed(evt);
            }
        });

        Extrato.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        Extrato.setForeground(new java.awt.Color(16, 124, 65));
        Extrato.setText("Extrato");

        jScrollPane1.setBorder(null);

        jList1.setBackground(new java.awt.Color(237, 237, 237));
        jList1.setBorder(null);
        jList1.setFont(new java.awt.Font("Poppins", 0, 11)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };

            public int getSize() {
                return strings.length;
            }

            public String getElementAt(int i) {
                return strings[i];
            }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.setFocusable(false);
        jList1.setInheritsPopupMenu(true);
        jList1.setOpaque(false);
        jList1.setRequestFocusEnabled(false);
        jList1.setSelectionBackground(new java.awt.Color(16, 124, 65));
        jList1.setSelectionForeground(new java.awt.Color(255, 255, 255));
        jList1.setVerifyInputWhenFocusTarget(false);
        jList1.setVisibleRowCount(5);
        jScrollPane1.setViewportView(jList1);
        jScrollPane1.setVerticalScrollBarPolicy(ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setHorizontalScrollBarPolicy(ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(216, 216, 216)
                                                .addComponent(jLabel3)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(nameuser)
                                                        .addComponent(moneyuser))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(Extrato)
                                                .addGap(226, 226, 226))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel1)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButton2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 185,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButton1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 185,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addComponent(CreateAccount,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 185,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39,
                                                        Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(37, 37, 37)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(nameuser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(moneyuser)
                                        .addComponent(Extrato))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel1)
                                                .addGap(26, 26, 26)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                46, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(CreateAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        172, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jScrollPane1)
                                                .addGap(18, 18, 18)))
                                .addComponent(jLabel3)
                                .addGap(20, 20, 20)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startUpdatingExtrato(String numeroContaArmazenada) {
        ScheduledExecutorService scheduler = Executors.newSingleThreadScheduledExecutor();
        scheduler.scheduleAtFixedRate(() -> showExtrato(numeroContaArmazenada), 0, 2, TimeUnit.SECONDS);
    }

    private void showExtrato(String numeroContaArmazenada) {
        try {
            String url = "http://localhost:8080/transacoes/extrato/" + numeroContaArmazenada;

            HttpRequest request = HttpRequest.newBuilder()
                    .uri(URI.create(url))
                    .build();

            HttpClient client = HttpClient.newHttpClient();
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());

            if (response.statusCode() == 200) {
                JSONArray extrato = new JSONArray(response.body());

                DefaultListModel<String> model = new DefaultListModel<>();

                for (int i = 0; i < extrato.length(); i++) {
                    JSONObject transacao = extrato.getJSONObject(i);

                    JSONObject contaOrigem = transacao.getJSONObject("contaOrigem");
                    JSONObject contaDestino = transacao.getJSONObject("contaDestino");

                    String contaOrigemNumero = contaOrigem.optString("numero", "Desconhecida");
                    String contaDestinoNumero = contaDestino.optString("numero", "Desconhecida");
                    double valor = transacao.optDouble("valor", 0.0);

                    if (numeroContaArmazenada.equals(contaOrigemNumero)
                            || numeroContaArmazenada.equals(contaDestinoNumero)) {
                        String extratoMensagem;

                        if (numeroContaArmazenada.equals(contaOrigemNumero)) {
                            extratoMensagem = String.format("-> Você enviou R$%.2f para %s", valor,
                                    contaDestinoNumero);
                        } else {
                            extratoMensagem = String.format("<- Você recebeu R$%.2f do %s", valor,
                                    contaOrigemNumero);
                        }

                        model.addElement(extratoMensagem);
                    }
                }

                if (model.isEmpty()) {
                    model.addElement("Suas transições aparecerá aqui!");
                }

                jList1.setModel(model);

                jList1.setCellRenderer(new DefaultListCellRenderer() {
                    @Override
                    public Component getListCellRendererComponent(JList<?> list, Object value, int index,
                            boolean isSelected, boolean cellHasFocus) {
                        JLabel label = (JLabel) super.getListCellRendererComponent(list, value, index, isSelected,
                                cellHasFocus);

                        if (isSelected) {
                            label.setBackground(label.getBackground().darker());
                        }

                        return label;
                    }
                });
            } else {
                System.out.println("Falha ao obter extrato: " + response.statusCode());
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isTransferUserOpen) {
            isTransferUserOpen = true;
            TransferUser transfer = new TransferUser();
            transfer.setVisible(true);

            transfer.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    isTransferUserOpen = false;
                }
            });
        }
    }// GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isInfoUserOpen) {
            isInfoUserOpen = true;
            InfoUser infoUserWindow = new InfoUser();
            infoUserWindow.setVisible(true);

            infoUserWindow.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    isInfoUserOpen = false;
                }
            });
        }
    }// GEN-LAST:event_jButton1ActionPerformed

    private void CreateAccountActionPerformed(java.awt.event.ActionEvent evt) {
        if (!isCreateAccountOpen) {
            isCreateAccountOpen = true;
            CreateAccount createInfo = new CreateAccount();
            createInfo.setVisible(true);

            createInfo.addWindowListener(new java.awt.event.WindowAdapter() {
                @Override
                public void windowClosed(java.awt.event.WindowEvent e) {
                    isCreateAccountOpen = false;
                }
            });
        }
    }// GEN-LAST:event_CreateAccountActionPerformed

    private void setIcon() {
        try {
            String iconPath = "src/main/java/com/atividade/appbank/icons/logo.png";
            setIconImage(new ImageIcon(iconPath).getImage());
        } catch (Exception e) {
            System.out.println("Erro ao carregar o ícone: " + e.getMessage());
        }
    }

    public void setUserInfo(String name, double money, String tipoConta) {
        nameuser.setText("Olá, " + name);
        moneyuser.setText("Saldo: R$ " + String.format("%.2f", money));
        jLabel1.setText("Conta: " + tipoConta);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfaceUserLog.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfaceUserLog.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfaceUserLog.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfaceUserLog.class.getName()).log(java.util.logging.Level.SEVERE,
                    null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfaceUserLog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateAccount;
    private javax.swing.JLabel Extrato;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel moneyuser;
    public javax.swing.JLabel nameuser;
    // End of variables declaration//GEN-END:variables
}
