/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.atividade.appbank.AccountUser;

import org.json.JSONObject;

import javax.swing.*;

import java.awt.*;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.io.File;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.text.SimpleDateFormat;
import java.util.Date;

import static com.atividade.appbank.AppBank.numeroContaArmazenada;
import static com.atividade.appbank.AppBank.respostaArmazenada;

/**
 *
 * @author Eliseu
 */
public class TransferUser extends javax.swing.JFrame {

    /**
     * Creates new form TransferUser
     */
    public TransferUser() {
        initComponents();
        setIcon();
        setLocationRelativeTo(null);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        agenciaUpdate1.setText(respostaArmazenada.split("\"agencia\":\"")[1].split("\"")[0]);
        agenciaUpdate.setText(numeroContaArmazenada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        descrition = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        agenciaUpdate1 = new javax.swing.JTextField();
        agenciaUpdate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        AgenciaAcc = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        MoneyValue1 = new javax.swing.JTextField();
        EnviarMoney = new javax.swing.JButton();
        MetodoTED = new javax.swing.JCheckBox();
        MetodoPIX = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        AgenciaAccountDestin = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        saldook = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QBank Transferência");
        setMinimumSize(new java.awt.Dimension(500, 600));
        setResizable(false);

        title.setFont(new java.awt.Font("Poppins", 1, 18)); // NOI18N
        title.setForeground(new java.awt.Color(16, 124, 65));
        title.setText("QBank Transferência");

        descrition.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        descrition.setText("Todos os dados do banco QBank estão em constância segurança.");

        jLabel1.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel1.setText("Agência");

        jLabel2.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel2.setText("N° da conta");
        setPlaceholder(AgenciaAccountDestin, "929601");

        agenciaUpdate1.setEditable(false);
        agenciaUpdate1.setText("{agencia}");
        agenciaUpdate1.setBorder(null);
        agenciaUpdate1.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        agenciaUpdate1.setEnabled(false);
        agenciaUpdate1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agenciaUpdate1ActionPerformed(evt);
            }
        });

        agenciaUpdate.setEditable(false);
        agenciaUpdate.setText("{numero}");
        agenciaUpdate.setBorder(null);
        agenciaUpdate.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        agenciaUpdate.setEnabled(false);
        agenciaUpdate.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        agenciaUpdate.setSelectionColor(new java.awt.Color(0, 0, 0));
        agenciaUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agenciaUpdateActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel3.setText("Agência*");
        setPlaceholder(AgenciaAcc, "763");

        AgenciaAcc.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel4.setText("Valor*");
        setPlaceholder(MoneyValue1, "50,00");

        MoneyValue1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoneyValue1ActionPerformed(evt);
            }
        });

        EnviarMoney.setBackground(new java.awt.Color(16, 124, 65));
        EnviarMoney.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        EnviarMoney.setForeground(new java.awt.Color(255, 255, 255));
        EnviarMoney.setText("Enviar Saldo");
        EnviarMoney.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnviarMoneyActionPerformed(evt);
            }
        });

        MetodoTED.setText("Ted");
        MetodoTED.setBorder(null);

        MetodoPIX.setText("Pix");
        MetodoPIX.setBorder(null);
        MetodoPIX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetodoPIXActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel5.setText("Método de Transferência");

        AgenciaAccountDestin.setFont(new java.awt.Font("Poppins", 0, 12)); // NOI18N
        AgenciaAccountDestin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgenciaAccountDestinActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Poppins", 1, 12)); // NOI18N
        jLabel6.setText("N° da Conta");

        File file = new File("src/main/java/com/atividade/appbank/images/logo.png");
        if (file.exists()) {
            jLabel7.setIcon(new ImageIcon(file.getAbsolutePath()));
        }

        if (respostaArmazenada.contains("\"saldo\":")) {
            String saldoString = respostaArmazenada.split("\"saldo\":")[1].split(",")[0].trim();

            double saldo = Double.parseDouble(saldoString);

            java.text.DecimalFormat df = new java.text.DecimalFormat("#,###.00");
            String saldoFormatado = df.format(saldo).replace('.', ',');

            saldook.setText("R$ " + saldoFormatado);
        } else {
            saldook.setText("Saldo não disponível");
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(44, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(MetodoPIX)
                                                        .addComponent(MetodoTED)
                                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                .addContainerGap())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(saldook)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(2, 2, 2)
                                                                .addGroup(layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jLabel4)
                                                                        .addComponent(descrition,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                420,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel1)
                                                                                        .addComponent(agenciaUpdate1,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                89,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addGap(64, 64, 64)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel2)
                                                                                        .addComponent(agenciaUpdate,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                103,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addComponent(EnviarMoney,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                153,
                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel3)
                                                                                        .addComponent(AgenciaAcc,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                155,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                                .addGroup(layout.createParallelGroup(
                                                                                        javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jLabel6)
                                                                                        .addComponent(
                                                                                                AgenciaAccountDestin,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                                                158,
                                                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                        .addGroup(layout.createSequentialGroup()
                                                                                .addComponent(jLabel7)
                                                                                .addPreferredGap(
                                                                                        javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                .addComponent(title))))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                                .createSequentialGroup()
                                                                .addComponent(MoneyValue1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 327,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(95, 95, 95)))
                                                .addGap(34, 34, 34)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(title))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(descrition)
                                                .addGap(29, 29, 29)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(agenciaUpdate1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(agenciaUpdate,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 32,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AgenciaAcc, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(AgenciaAccountDestin,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(MoneyValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 33,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(saldook)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(MetodoTED)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(MetodoPIX)
                                .addGap(36, 36, 36)
                                .addComponent(EnviarMoney, javax.swing.GroupLayout.PREFERRED_SIZE, 46,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(59, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agenciaUpdate1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_agenciaUpdate1ActionPerformed

    }// GEN-LAST:event_agenciaUpdate1ActionPerformed

    private void agenciaUpdateActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_agenciaUpdateActionPerformed
    }// GEN-LAST:event_agenciaUpdateActionPerformed

    private void MoneyValueActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MoneyValueActionPerformed
    }// GEN-LAST:event_MoneyValueActionPerformed

    private void MoneyValue1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MoneyValue1ActionPerformed
    }// GEN-LAST:event_MoneyValue1ActionPerformed

    private void MetodoPIXActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MetodoPIXActionPerformed
    }// GEN-LAST:event_MetodoPIXActionPerformed

    private void AgenciaAccountDestinActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AgenciaAccountDestinActionPerformed
    }// GEN-LAST:event_AgenciaAccountDestinActionPerformed

    private void EnviarMoneyActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            String numeroContaOrigem = numeroContaArmazenada;
            String agenciaOrigem = agenciaUpdate1.getText().trim();
            String numeroContaDestino = AgenciaAccountDestin.getText().trim();
            String agenciaDestino = AgenciaAcc.getText().trim();
            String tipo = MetodoTED.isSelected() ? "TED" : MetodoPIX.isSelected() ? "PIX" : null;

            if (agenciaOrigem.isEmpty() || numeroContaDestino.isEmpty() || agenciaDestino.isEmpty() || tipo == null) {
                JOptionPane.showMessageDialog(this,
                        "Por favor, preencha todos os campos obrigatórios e selecione um método de transferência.",
                        "Erro", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (numeroContaOrigem.equals(numeroContaDestino)) {
                JOptionPane.showMessageDialog(this, "Você não pode transferir para sua própria conta.", "Erro",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            double valor;
            try {
                valor = Double.parseDouble(MoneyValue1.getText().replace(",", "."));
                if (valor <= 0)
                    throw new NumberFormatException();
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Insira um valor válido maior que zero.", "Erro",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            // Extrair saldo da resposta armazenada
            double saldoContaOrigem = 0.0;

            try {
                JSONObject jsonObject = new JSONObject(respostaArmazenada);
                saldoContaOrigem = jsonObject.optDouble("saldo", 0.0);

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Erro ao acessar o saldo da conta.", "Erro",
                        JOptionPane.ERROR_MESSAGE);
                this.dispose();
                return;
            }

            if (saldoContaOrigem == 0.0) {
                JOptionPane.showMessageDialog(this, "Saldo insuficiente. Sua conta não possui saldo disponível.",
                        "Erro",
                        JOptionPane.ERROR_MESSAGE);
                this.dispose();
                return;
            }

            if (valor > saldoContaOrigem) {
                JOptionPane.showMessageDialog(this, "Saldo insuficiente para realizar esta transação.", "Erro",
                        JOptionPane.ERROR_MESSAGE);
                this.dispose();
                return;
            }

            // Preparar dados da transação
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss");
            String dataHora = sdf.format(new Date());

            JSONObject json = new JSONObject();
            json.put("contaOrigem", new JSONObject().put("agencia", agenciaOrigem).put("numero", numeroContaOrigem));
            json.put("contaDestino", new JSONObject().put("agencia", agenciaDestino).put("numero", numeroContaDestino));
            json.put("valor", valor);
            json.put("dataHora", dataHora);
            json.put("tipo", tipo);

            String url = "http://localhost:8080/transacoes/deposito/" + numeroContaOrigem;
            HttpURLConnection con = (HttpURLConnection) new URL(url).openConnection();
            con.setRequestMethod("POST");
            con.setRequestProperty("Content-Type", "application/json");
            con.setDoOutput(true);

            try (OutputStream os = con.getOutputStream()) {
                os.write(json.toString().getBytes(StandardCharsets.UTF_8));
            }

            int responseCode = con.getResponseCode();
            if (responseCode == HttpURLConnection.HTTP_OK || responseCode == HttpURLConnection.HTTP_CREATED) {
                JOptionPane.showMessageDialog(this, "Transferência realizada com sucesso!", "Sucesso",
                        JOptionPane.INFORMATION_MESSAGE);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this,
                        "Erro ao realizar a transferência. Código de resposta: " + responseCode, "Erro",
                        JOptionPane.ERROR_MESSAGE);
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocorreu um erro ao processar a transferência: " + e.getMessage(),
                    "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void setPlaceholder(JTextField textField, String placeholder) {
        Font poppinsFont = new Font("Poppins", Font.ITALIC, 12);
        textField.setText(placeholder);
        textField.setForeground(Color.GRAY);
        textField.setFont(poppinsFont);

        textField.addFocusListener(new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                if (textField.getText().equals(placeholder)) {
                    textField.setText("");
                    textField.setForeground(Color.BLACK);
                    textField.setFont(new Font("Poppins", Font.BOLD, 12));

                }
            }

            @Override
            public void focusLost(FocusEvent e) {
                if (textField.getText().isEmpty()) {
                    textField.setText(placeholder);
                    textField.setForeground(Color.GRAY);
                    textField.setFont(poppinsFont);
                }
            }
        });
    }

    private void setIcon() {
        try {
            String iconPath = "src/main/java/com/atividade/appbank/icons/logo.png";
            setIconImage(new ImageIcon(iconPath).getImage());
        } catch (Exception e) {
            System.out.println("Erro ao carregar o ícone: " + e.getMessage());
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransferUser.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransferUser.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransferUser.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransferUser.class.getName()).log(java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransferUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AgenciaAcc;
    private javax.swing.JTextField AgenciaAccountDestin;
    private javax.swing.JButton EnviarMoney;
    private javax.swing.JCheckBox MetodoPIX;
    private javax.swing.JCheckBox MetodoTED;
    private javax.swing.JTextField MoneyValue1;
    private javax.swing.JTextField agenciaUpdate;
    private javax.swing.JTextField agenciaUpdate1;
    private javax.swing.JLabel descrition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel saldook;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
